config/routes.rb
Rails.application.routes.draw do
  resources :photos, only: [:index, :show]
  root 'photos#index'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  require 'flickraw'

  before_action :set_flickr, only: [:index]

  def index
  	if params[:search]
  	  @user = flickr.people.getInfo(:user_id => params[:search])
  	  @user_photos = flickr.photos.search(:user_id => params[:search])
   	  @user_photos_urls = []

   	  @user_photos.each do |photo|
  	    @user_photos_urls << FlickRaw.url(photo)
  	  end
    end
  end


  private

	def set_flickr
	  FlickRaw.api_key = ENV['API_KEY']
	  FlickRaw.shared_secret = ENV['SHARED_SECRET']

	  flickr.access_token = ENV['ACCESS_TOKEN']
	  flickr.access_secret = ENV['ACCESS_SECRET']
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlickrStream</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Julius+Sans+One' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Catamaran:200' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/_search.html.erb
<div class="search">
  <%= form_tag(photos_path, :method => "get") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Enter a User ID" %>
    <%= submit_tag "Search", :name => nil, :class => "button" %>
  <% end %>
</div>

app/views/photos/_search_results.html.erb
<div class="search-results">
  <% if @user %>
    <h1 class="title"><%= @user.username %>'s photos</h1>
    <% @user_photos_urls.each do |url| %>
      <tr>
        <td><%= link_to( image_tag(url), url, :class => "picture" ) %></td>
	    
      </tr>
    <% end %>
  <% end %>
</div>

app/views/photos/index.html.erb
<div class="container">
  <h1 id="logo">Flickr Flickr Hurra</h1>
  <%= render 'search' %>
  <p>Go to <%=link_to "idGettr", "http://idgettr.com/", :target => "_blank" %> to get the Flickr ID</p>
  <%= render 'search_results' %>
</div>